# Waiting to see what happens with docker-compose-ui support in order to move to 3.8
#   https://github.com/francescou/docker-compose-ui/issues/120
#   https://github.com/francescou/docker-compose-ui/issues/110
version: "3.6"

networks:
  compose_pt-net:
    external: true

services:
  #selenium-hub:
  #  image: selenium/hub:3.141.59-bismuth
  #  container_name: selenium-hub
  #  networks:
  #    compose_pt-net:
  #  ports:
  #    - "4444:4444"
  chrome:
    # Use the -debug image instead, along with the 5900 port range if you want to VNC into the container and view the browser.
    # https://github.com/SeleniumHQ/docker-selenium#debugging
    #image: selenium/standalone-chrome-debug # The tags are different for -debug
    image: selenium/standalone-chrome:91.0 # Published 27 May 2021
    networks:
      compose_pt-net:
    ports:
      - "4444-4455:4444"
      #- "5900-5901:5900"
    shm_size: 1G
    # Uncomment the SE_OPTS env var to enable debug logs in Selenium containers.
    #environment:
    #  - SE_OPTS=-debug
  firefox:
    # Use the -debug image instead, along with the 5900 port range if you want to VNC into the container and view the browser.
    # https://github.com/SeleniumHQ/docker-selenium#debugging
    #image: selenium/standalone-firefox-debug # The tags are different for -debug
    image: selenium/standalone-firefox:88.0 # Published 27 May 2021
    networks:
      compose_pt-net:
    ports:
      - "4444-4455:4444"
      #- "5900-5901:5900"
    shm_size: 1G
    # Uncomment the SE_OPTS env var to enable debug logs in Selenium containers.
    #environment:
    #  - SE_OPTS=-debug

